listen_host: 0.0.0.0
listen_port: 3000

metrics_port: 3001

app_name: codebase-rest-nodejs-typescript

publicapis_host: https://api.publicapis.org

db:
  mongo:
    host: localhost
    port: 27017
    database: someDBName
    pool:
      max_size: 7
  mariadb:
    host: localhost
    port: 3306
    database: codebase
    password: codebase
    pool:
      max_size: 7
